"""initial migrations

Revision ID: ca7d8d88ac86
Revises: b3a92d6c9569
Create Date: 2023-01-29 16:47:12.085605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7d8d88ac86'
down_revision = 'b3a92d6c9569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addproduct', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'brand', ['brand_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('f_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.drop_column('f_name')

    with op.batch_alter_table('addproduct', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'brand', ['brand_id'], ['id'])

    # ### end Alembic commands ###
